#pragma once

#define GLFW_INCLUDE_VULKAN
#define GLM_FORCE_RADIANS
#define GLM_FORCE_DEFAULT_ALIGNED_GENTYPES
#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#define GLM_ENABLE_EXPERIMENTAL
// #define SHOW_FRAME_RATE
#include "algorithm"
#include "any"
#include "array"
#include "chrono"
#include "cstdlib"
#include "cstring"
#include "fstream"
#include "functional"
#include "glm/glm.hpp"
#include "glm/gtc/matrix_access.hpp"
#include "glm/gtc/matrix_inverse.hpp"
#include "glm/gtc/matrix_transform.hpp"
#include "glm/gtc/random.hpp"
#include "glm/gtc/type_ptr.hpp"
#include "glm/gtx/string_cast.hpp"
#include "iostream"
#include "ktx.h"
//#include "ktxvulkan.h"
#include "limits"
#include "map"
#include "memory"
#include "optional"
#include "set"
#include "stdexcept"
#include "thread"
#include "tiny_obj_loader.h"
#include "tinygltf/tiny_gltf.h"
#include "unordered_map"
#include "vector"
#include <GLFW/glfw3.h>
#include <glm/gtx/hash.hpp>
